index.js
test/test.js

Synchronize the `aria-checked` state of menu items when an item is selected. Also includes a test for the updating the button label with the selected item's text.

Manage checked menu item state

---

index.js

It does default to `menu` but would be good to be explicit. 🙆 
https://www.w3.org/TR/wai-aria-1.1/#aria-haspopup

Change haspopup value to menu

---

index.js
test/test.js

This prevents items with `aria-disabled="true"` from being triggered.
@dgraham I noticed that the arrow navigation will get stuck because `button[disabled]` is not focusable. We will need to [filter out `[disabled]`](https://github.com/github/details-menu-element/blob/38bd3dc0af7934029b9e41c89fe3a317ef659c42/index.js#L67) to fix it. 
That makes me wonder if we should match this non-focusable behavior on `aria-disabled=true` items. This would mean not only filtering it out, but also requiring `tabindex="-1"` on `focusable[aria-disabled="true"]` items so it escapes <kbd>tab</kbd> focus. 
And then we will end up with 🤔 
```javascript
details.querySelectorAll('[role^="menuitem"]:not([hidden]):not([disabled]):not([aria-disabled="true"])')
```
What do you think?
This isn't a problem for …

Support disabled menuitem 

---

index.js
test/test.js

- New cancellable `details-menu-select` event instead of changing the existing event for compatibility
- For `menuitemcheckbox` I think by default menu just shouldn't be closed

Add details-menu-select and prevent closing on menuitemcheckbox click

---

index.js

I noticed that `details-menu-select` is being fired twice on <kbd>Enter/Space</kbd> `keydown` but not on click. In the <kbd>Enter/Space</kbd> handler we call `commit()`, and then `click()` which triggers another `commit()`. 
This removes the first `commit()` so whatever comes with the native click binding on the element still happens. For example <kbd>Space</kbd>(which by default doesn't trigger `<a>`) on `<a role="menuitem">` should navigate + `commit`, as a click would.
I tried to add a test case but couldn't simulate the native `Enter` event.

Prevent committing twice on keydown

---

index.js
test/test.js

A menu can have only disabled menu items for valid reasons (perhaps dynamically enabled). In this case the code should just not move focus, instead of throwing an exception.

Fix exception thrown when no menu items are found

---

README.md
examples/index.html
index.js
test/test.js

`details-menu` supports `role=menuitemcheckbox`, and we started to use this markup to leverage native label/input checking behavior:
```html
<label tabindex="0" role="menuitemcheckbox" aria-checked="true">
<input type="checkbox" checked> Menu item
</label>
```
I noticed two issues when we use this markup:
1. `details-menu-select` event is fired twice on label click
> When a `<label>` is clicked or tapped and it is associated with a form control, **the resulting click event is also raised for the associated control**. [(ref)](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#Usage_notes)
2. `aria-checked` is always true (even when checkbox is unchecked)
On select, `aria-checked` is hardcoded to be `true` instead of toggling.
See the failed test cases for reproduction steps. …

Fix checkboxes

---

examples/index.html
index.js
test/test.js

In #16 I added `label > input` markup constraint to `menuitemradio` and `menuitemcheckbox`. However we later found out that there are many cases of `<button type="submit" role="menuitemradio" name="type" value="csv">` which acts like radio buttons but submits without refreshing the page.
This adds support for these buttons, but keep the constraint for `menuitemcheckbox` as checkbox states are more flexible than radios. For example, with named radio inputs, we can assume all items but the selected one is unchecked, but that is not the case for checkbox inputs.

Support buttons as menuitemradio

---

LICENSE
index.js
test/test.js

Adds up and down arrow navigation on closed menu buttons according to the WAI-ARIA [keyboard navigation recommendations](https://www.w3.org/TR/wai-aria-practices/#menubutton).
> (Optional) Down Arrow: opens the menu and moves focus to the first menu item.
> (Optional) Up Arrow: opens the menu and moves focus to the last menu item.

Open menu and focus item on arrow navigation

---

README.md
index.js
index.js.flow
test/test.js

Adds a boolean preload attribute to load deferred menu content on mouse hover, improving perceived performance.

Fetch deferred menu content on mouse hover

---

index.js
test/test.js

When preloading menu content with an `<include-fragment>`, ignore any additional `<include-fragment>` children included in the server response.

Preload only one <include-fragment>

---

index.js
test/test.js

Hi! 👋 
In order to not close dialog elements that contain open details menu elements we shouldn't propagate the keydown event if we are closing the menu.
This PR stops event propagation on keydown events if it's <kbd>Esc</kbd>.

Don't propagate ESC keydown event

---

README.md
index.js
test/test.js

Ref: https://github.com/github/web-systems/issues/190#issuecomment-472536055
- both events now do not bubble
- `event.detail` now contain `relatedTarget` which is the selected item
```js
document.addEventListener('details-menu-selected', event => {
console.log(event.target) // details-menu
console.log(event.detail.relatedTarget) // selected item
}, true)
```
> When an element can contain itself as a child, like `<details>`, it makes sense to not bubble to avoid accidentally targeting the wrong element in a delegated event listener. (https://github.com/github/task-lists-element/pull/5#discussion_r266524615)
We have cases of `details-menu details-dialog details-menu` on github.com.

Update events and docs (breaking change)

---

index.js
package-lock.json
test/test.js

Fixes #28.
https://travis-ci.org/github/details-menu-element/builds/530352904#L555-L561
Order of events:
1. Initial `<label>` `click`
2. `<input type=radio>` `click`, triggered by `<label>` `click` [per spec](https://html.spec.whatwg.org/multipage/forms.html#the-label-element)
2. `<input type=radio>` `change`
Problem occurs because all 3 of these events called `commit()`.
When `click`, check if a `change` event should happen. If it should, ignore `click` (the first two events).

Fix radio input check triggering multiple details-menu-select events

---

index.js
test/test.js

Fixes #30. Only prevent event propagation if the parent `<details>` is open.

Fix escape keydown trapping

---

index.js
test/test.js

This is so that the ARIA attribute correctly reflects the input's state.

Support input.indeterminate

---

examples/index.html
index.js
test/test.js

- Respect `[autofocus]:not([role^="menuitem"])` items when menu is toggled
- Respect existing `[role]` on `<details-menu>`
- Set `role="button"` on `<summary>` ref: https://github.com/github/details-dialog-element/issues/34. 
> Per the manner in which the summary element is exposed to Safari's Webkit (announced as "summary" but no matching ARIA role) and Blink (announced as and reported as a "DisclosureTriangle"role) these "buttons" are not discoverable when navigating by form controls or button elements with VoiceOver on macOS or iOS.
- Remove list markup from demo page– accessibility tree comparison:
|before|after|
|-|-|
|<img width="382" alt="image" src="https://user-images.githubusercontent.com/1153134/64562306-b58c6c00-d31a-11e9-8062-ee9be81007e0.png">|<img width="393" alt="image" …

Fix focus and role problems

---

index.js

For reference: https://github.com/github/web-systems/issues/228.
Like #38 and #39 this aims to better support having text inputs inside of `<details-menu>`. This one can be merged independently. 
For background on this approach, refer to the research I've done when fixing https://github.com/github/combobox-nav/pull/2. (`event.isComposing` is not supported in non-Chromium Edge)
You can test this locally with an IME of your choosing and with this simple markup:
```html
<details open>
<summary>Best robot: <span data-menu-button>Unknown</span></summary>
<details-menu>
<input autofocus>
<button type="button" role="menuitem" data-menu-button-text>Hubot</button>
<button type="button" role="menuitem" data-menu-button-text>Bender</button>
<button type="button" role="menuitem" …
```

Prevent keyboard events during text composition inside of details-menu

---

index.js

Reference: https://github.com/github/github/pull/133881
Issue: Menu button was focused on when one of its menuitems was triggered by a hotkey without the menu being open.
Steps to reproduce:
1. Trigger a click on a menu item without the menu being open
2. See `<summary>` gets focused
This fixes the issue by returning the `close()` call if `<details>` isn't open.
|before|after|
|-|-|
|![](https://cl.ly/e1e80499dd1a/Screen%20Recording%202020-01-29%20at%2011.39.gif)|![](https://cl.ly/590b92b1fdbf/Screen%20Recording%202020-01-29%20at%2011.39.gif)|
I didn't add a test because this would be testing that something _doesn't_ happen which can potentially be any number of things.
cc @latentflip

Only trigger close if details was open

---

examples/index.html
src/index.ts
test/test.js

If the dropdown itself is the `autofocus` field in the page, then `<details-menu>` fails to set focus to any other `autofocus` element in the popup when displaying it.
Reason being that the selector matches first the `<summary>` and wrongly sets focus to it instead of any `autofocus` element inside the `details-menu`.
An example was added to demonstrate the issue. It fails currently using the `@latest` version, but it's fixed when using `dist`.

Autofocus fix

---

src/index.ts
test/test.js

We rely on change to commit the click on radio inputs, but change event won't happen if the item is already checked so shortcutting in that case to commit directly and close the menu.

Close popup when checked item is clicked.

---

examples/index.html
src/index.ts

The logic that closes the menu when clicking a checked input assumes that clicks happen on a `<label>`, but actually if the label contains other elements, that click may come from them, like a `<span>`.
So instead of comparing target with label (`menuitem`), the new approach is comparing with `input`.
I've used `npm link` to verify that this fix works in dotcom.
Most of the changes in HTML were made by Prettier.
The only actual change is adding <span> to reproduce the issue this PR fixes.

Support click from nested elements

---

examples/index.html
src/index.ts
test/test.js

This PR makes updates to ensure that aria-disabled menu items are arrow-key navigable. 
We discovered that a `menuitem` with `aria-disabled="true"` cannot currently be accessed with arrow key navigation, and can only be accessed through tab navigation. Even with `aria-disabled="true"`, the menu item should be reachable with arrow key navigation.
In the following video, I navigate through an example I've added to `index.html` with a menu item that includes `aria-disabled="true"`. I am able to navigate through it using arrow key nav.
https://user-images.githubusercontent.com/16447748/197544785-8bb1f81e-745c-41bc-a136-972ddaa7a5cb.mov
From our internal accessibility slack thread regarding disabled menu items:
> If used, disabled controls must be user-addressable if they make up a set.  Think …

Allow arrow key navigation on aria-disabled elements

---

.devcontainer/Dockerfile
package-lock.json
package.json
test/karma.config.cjs

I'm working on adding [trusted types compatibility](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/trusted-types) to this package and wasn't able to run the tests in a codespace because chrome wouldn't start. I looked at auto-complete-element and [changing the installation](https://github.com/github/auto-complete-element/pull/88) of chrome seemed to fix the problem in this project too.

Install chrome in codespaces via Dockerfile rather than use node-chrmium package
